/**
 * pi-copium — data constants
 */

// --- TAGLINES ---
export const TAGLINES = [
  "certified yolo certified",
  "close enough is production-ready",
  "huffing copium since {current year}",
  "it compiles. ship it.",
  "it works on my machine",
  "LGTM (i didn't read it)",
  "powered by vibes and denial",
  "quality: lol",
  "read the comments (there are none)",
  "tests? never heard of em",
  "the agent is always right (it isn't)",
  "trust the process (there is no process)",
  "vibes-based architecture",
];

// --- WORKING MESSAGES ---
export const WORKING_MESSAGES = [
  "brain cells leaving the chat...",
  "cooking...",
  "coping...",
  "it's giving engineer...",
  "locking in...",
  "me when the tests pass...",
  "testing in prod...",
  "touching grass...",
  "burning tokens responsibly...",
  "charging the crystal ball...",
  "compiling vibes...",
  "consulting the spirits...",
  "copying from a smarter model...",
  "cringing...",
  "deleting evidence...",
  "flipping a coin...",
  "guessing with confidence...",
  "hallucinating (as a treat)...",
  "reading the docs (jk)...",
  "refusing to elaborate...",
  "shaking the magic 8-ball...",
  "stealing from stackoverflow (spiritually)...",
  "struggling silently...",
  "thinking about thinking...",
  "throwing stuff at the wall...",
  "winging it...",
  "blaming the training data...",
  "browsing stackoverflow with extra steps...",
  "debugging with print statements...",
  "faking competency...",
  "generating text, questioning life...",
  "hoping for the best...",
  "learning on the job...",
  "making it up as i go...",
  "one more token bro...",
  "sending it...",
  "sweating in fp16...",
];
